### ISSUE TITLE
Scaffold SessionManagerField

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#11]
### Overview
Perquisite work to build out a new CMS component to display session data in the Member admin UI.

See https://github.com/silverstripe/silverstripe-session-manager/issues/12 for the designs and more details.

### Acceptance Criteria

- [x]  Set up build tooling
    - Base configuration on [Module Template](https://github.com/silverstripe/silverstripe-module)
    - Use current release of silverstripe-webpack
- [x]  Create empty SessionManagerField component and Entwine wrapper
- [x]  Create basic SessionManagerField PHP class
- [x]  Create extension to attach SessionManagerField to Member UI
- [x]  Validate that new field is rendering correctly
- [x]  By default this component is viewed by the current user only 

### Notes
- The module template has some out of date dependencies that will need updating as part of this issue. Let’s look to commit the updates back into the module template repository.

**Comment by Cheddam** [comment]
Shifted final AC regarding position of field to #12. The scaffolding PR will be merged alongside the PR for that issue.
