### ISSUE TITLE
Link in readme forwards to a page that doesn't exist

### ISSUE THREAD

**Issue by adunn49** [kinglozzer/silverstripe-session-manager#172]
# Description
There is a 'Managing Sessions' link in the readme that, when clicked on, forwards to the live cms documentation and returns 'page not found'.

## Screenshot of link (highlighted) :

<img width="756" alt="Screenshot 2023-11-03 at 9 56 42 AM" src="https://github.com/silverstripe/silverstripe-session-manager/assets/21965646/9b193097-f11b-45e7-8dcc-8100ad35ed10">

## Result when link is clicked
<img width="896" alt="Screenshot 2023-11-03 at 9 54 28 AM" src="https://github.com/silverstripe/silverstripe-session-manager/assets/21965646/c4d28cd7-8b2d-4d13-b689-1e8ba1aa5b7c">

## PR
- https://github.com/silverstripe/silverstripe-session-manager/pull/173

**Comment by GuySartorelli** [comment]
PR merged
