### ISSUE TITLE
New queued job

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#22]
### Overview
Garbage collection was recently moved to a crontask for the session manager module, see https://github.com/silverstripe/silverstripe-session-manager/pull/9

This relies on the silverstripe/contask module being installed, which isn't a commonly used module, compared to symbiote/queuedjobs. 

For all sites, a new queued job should be created and added on dev build to ensure the garbage collection tasks can happen without additional Developer intervention.

### Acceptance Criteria
- [ ] If the queued job module is installed, a dedicated queued job for garbage collection is added to the project at the same time
- [ ] A Developer does not have to manually configure the queued job
- [ ] The queued job re-queues itself
- [ ] Validate that the crontask isn't required, and then remove that bit of code, opting to only have the queued job implementation
- [ ] Readme reflects how Developers should manage this task taking into account whether their project is using the queued jobs module or not

### Notes
- This work wouldn't assume that queued jobs should be a requirement of the session manager module. There is still the opportunity to manually schedule the task

### PRs
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/35

**Comment by brynwhyman** [comment]
From @maxime-rainville :

>I was just looking at the install stats for crontask vs queued jobs ... according packagist, queued jobs and crontask are about as popular. If anything crontask seems like it's gaining in popularity, while queued job is stagnating.
- https://packagist.org/packages/symbiote/silverstripe-queuedjobs/stats
- https://packagist.org/packages/silverstripe/crontask/stats
On our platforms, crontask actually has more installs than queued jobs. 754 vs 648

> My point is that my initial thought that we should prioritise Queued job over crontask was probably wrong.

On the note of: "Validate that the crontask isn't required", there are other modules that I expect suggest the use of queuedjobs but don't enforce it - we should see how they handle this. E.g.:
* advanced workflow: https://github.com/symbiote/silverstripe-advancedworkflow
* https://github.com/silverstripe/silverstripe-contentreview

**Comment by emteknetnz** [comment]
CWP Kitchen Sink module usage of queuedjobs vs crontask where both are required. Analysis of composer.lock:

### symbiote/silverstripe-queuedjobs

**require**
- bringyourownideas/silverstripe-composer-security-checker
- bringyourownideas/silverstripe-maintenance
- cwp/cwp-recipe-search
- silverstripe/gridfieldqueuedexport
- silverstripe/ldap
- symbiote/silverstripe-advancedworkflow

**suggest:**
- silverstripe/contentreview
- silverstripe/fulltextsearch
- silverstripe/recipe-form-building
 
### silverstripe/crontask

**require:**
- (none)

**suggest:**
- cwp/cwp
