### ISSUE TITLE
Date formatting and authenticated hours

### ISSUE THREAD

**Issue by emteknetnz** [kinglozzer/silverstripe-session-manager#41]
2 issues:
- Tooltip times are formatted in US time m/d/y despite being in nz locale
- "authenticated in 13 hours..." is nonsensical, no idea what this is supposed to mean.  Timing wise I had logged in within the previous hour.

![image](https://user-images.githubusercontent.com/4809037/112254326-4b9da280-8cc5-11eb-97bb-e954f6012453.png)

![image.png](https://images.zenhubusercontent.com/5dcb6f9e3c55460001028c42/c5e70be9-0563-4432-9198-a748d3f0e98f)

### Acceptance Criteria
- Date/ time format is updated based on CMS user's favoured locale (set in CMS profile section), or locale of the user
- "Authenticated in x" is changed to "Authenticated x ago" ([design reference](https://projects.invisionapp.com/share/ANZZEC4XUTQ#/screens/439163639_CMS_-_Login_-_Session_Management_-_Remove_A_Device_-_List))
- Ditto for last active
- The bug in calculated the timestamp when the authentication happened is fixed - it doesn't seem to be working based on this issue report.

### PRs
- [ ] https://github.com/silverstripe/silverstripe-session-manager/pull/52

**Comment by emteknetnz** [comment]
I've implemented the work, however there's a catch, with NZ date style by changing the Members Interface Language to `English (United Kingdom)` the dates break over multiple lines

![image](https://user-images.githubusercontent.com/4809037/113226668-363ffe00-92ed-11eb-95df-414a300d83d7.png)

Unfortunately there's not a lot we can do about this.  Bad options are:
a) Put a line break in the english translation string, however this means we'd need to use reacts 'dangerouslysetinnerhtml' attribute which opens a security hole of XSS attacks via translation strings
b) Globally change the width of the tooltip - which will affect all the other tooltips on the site.  This also means that it'll now just looking wonky using a US locale
c) Change the date format - we use 'L LT' throughout the site, so it wouldn't match the rest of the site

I'm inclined that a better option may be just to get rid of the tooltip and display this as regular text

@clarkepaul

**Comment by clarkepaul** [comment]
d) leave it as is... I'm okay with it as is @emteknetnz, its a minor thing as it is still readable. 

FYI @emteknetnz there is a quick way to break the line within a tooltip by adding `data-html="true"` then adding `<br>` between the dates.

**Comment by emteknetnz** [comment]
@clarkepaul yes `data-html="true"` does work, however the problem is that the `<br>` is set within a translation string.  What this means is that this create a security hole where a malicious user could submit a translation string containing a `<script>` and an XSS payload in a foreign language via transfix which could possible not get detected when we pull the translation strings.

**Comment by clarkepaul** [comment]
@emteknetnz okay makes sense

**Comment by brynwhyman** [comment]
Fixed in https://github.com/silverstripe/silverstripe-session-manager/pull/52
