### ISSUE TITLE
Folder/namespace renaming

### ISSUE THREAD

**Issue by emteknetnz** [kinglozzer/silverstripe-session-manager#42]
Should do this close to the conclusion of the feature dev so as not to cause any merge conflicts with open PRs

### ACs
- [x] Move contents of `Extension` folder to the `Extensions` folder and ensure namespace matches
- [x] Pluralise the following folders/namespaces to match the other folders - FormField, Job, Model, Service
- [x] Create Controllers folder, move LoginSessionController there, update namespace from /Control/ to /Controllers/
- [x] LoginSessionController - change class it extends from LeftAndMain to Controller, remove $ignore_menuitem config
- [x] Change LoginSessionMiddleware namespace from /Control/ to /Middleware/
- [x] Double check all other namespaces match folders
- [x] Remove unused class `SilverStripe\SessionManager\Forms\GridFieldRevokeLoginSessionAction`

### PRs
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/74

**Comment by maxime-rainville** [comment]
I've added an AC to remove the unused class `SilverStripe\SessionManager\Forms\GridFieldRevokeLoginSessionAction`
