### ISSUE TITLE
Non admin users logout

### ISSUE THREAD

**Issue by emteknetnz** [kinglozzer/silverstripe-session-manager#58]
Split off from https://github.com/silverstripe/silverstripe-session-manager/issues/46

Support for non-admin users to logout, which was the original reason for referencing `logout_across_devices` in the session-manager module

### PRs
- [ ] https://github.com/silverstripe/silverstripe-session-manager/pull/56 (now closed)

**Comment by brynwhyman** [comment]
@emteknetnz by 'non admin' users are you referring to users who have no access to the CMS (and their member UI)?

**Comment by emteknetnz** [comment]
@brynwhyman that's correct

Typical way these types of members exist are for sites that allow website users to create an account via the frontend which will create a corresponding record in the Member table.  User can log into their account, but that's also on the website frontend, not the CMS.  This means the Member table will be shared by both CMS and website users.

I'm not sure what a scenario is where you'd have CMS users without access to the CMS

We could make a decent argument that supporting website account users via session-manager is out of scope.

**Comment by maxime-rainville** [comment]
My general view is that we shouldn't officially support this use case, while not precluding devs from implementing it on their website. We don't provide any front features for Member management out-the-box.

There's some third party modules that allow you to implement front-end member areas with profile pages. e.g.
- https://github.com/ajshort/silverstripe-memberprofiles
- https://github.com/symbiote/silverstripe-memberprofiles

I think it would make more sense for them to implement and maintain this kind of feature.

**Comment by emteknetnz** [comment]
I'm closing this issue as it's unlikely to proceed
