### ISSUE TITLE
Add the standard silverstripe commercially supported GH labels

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#70]
This repo is still using the default GH labels. We should update this to use the standard GH labels, as used on the commercially supported modules. There's more flexibility on adding 'impact' and 'effort' among other things!

**Comment by ScopeyNZ** [comment]
`cow` does this: https://github.com/silverstripe/cow#synchronising-data-to-supported-modules

**Comment by GuySartorelli** [comment]
The labels on this module have been updated (not with cow, but still)
