### ISSUE TITLE
Remove revoke confirmation modal 

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#79]
There have been prior decisions made to not require a confirmation modal at the time that a user requests to revoke a session, see: https://github.com/silverstripe/silverstripe-session-manager/issues/37

However, this is a feature that's actually present in the module. This issue would cover removing it.

Revoking a session is a conscious action that should provide a streamlined process. Confirmation modals would usually be resolved for more destructive actions, for which this is not considered one.

Screenshot of current modal:
![image](https://user-images.githubusercontent.com/15868440/122138724-671ae280-ce9b-11eb-8de6-ac860521b29b.png)

### PRs
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/80

**Comment by emteknetnz** [comment]
But it is a destructive action?  I'm destroying a database record.

Maybe I want to be logged in with 2 browsers and I just misclicked the log out button?

**Comment by maxime-rainville** [comment]
All PRs have been merged.
