### ISSUE TITLE
Add session-manager docs to core

### ISSUE THREAD

**Issue by bergice** [kinglozzer/silverstripe-session-manager#85]
# Overview

With session-manager being included in the CMS recipe v4.9 it now makes sense to:
* move the developer docs to docs.silverstripe.org; and
* the userhelp guide outside of the 'Optional features' section in userhelp.silverstripe.org

There may also be other places that need updating in both docs resources, particularly around the "Keep me signed in" segments and Login segments.

**Comment by brynwhyman** [comment]
This happened in https://github.com/silverstripe/recipe-cms/issues/47
