### ISSUE TITLE
1.1.0 tag missing on Packagist

### ISSUE THREAD

**Issue by UndefinedOffset** [kinglozzer/silverstripe-session-manager#92]
It looks like Packagist didn't pickup the 1.1.0 for some reason, which is causing recipe-cms 4.9.0 to install 1.1.0-r1 of this package.

![Screenshot 2021-10-06 at 10-07-54 silverstripe session-manager - Packagist](https://user-images.githubusercontent.com/1391558/136208619-9cc1f164-ba55-49c5-9105-6e1f5f0d872d.png)

**Comment by emteknetnz** [comment]
Weird. I've manually refreshed it and now 1.1.0 is showing
